version: '3.1'
services:
  mongodb:
    image: mongo:noble
    environment:
      MONGO_INITDB_DATABASE: main
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: always

  nyan-send:
    build: .
    volumes:
      - nyan_data:/usr/src/app/.data
    depends_on:
      - mongodb
    restart: always
    environment:
      - OPENAI_API_KEY
      - HF_HOME=/usr/src/app/.data/hf
    deploy:
      resources:
        limits:
          cpus: "0.5"
    command: bash send_container.sh

  nyan-crawl:
    build: .
    volumes:
      - nyan_data:/usr/src/app/.data
    depends_on:
      - mongodb
    restart: always
    command: bash crawl.sh

volumes:
  mongo_data:
  nyan_data: